main()
{
	asm { @"10-5-2=" } 
	__outn(10-5-2); 
	asm { @"\n" }

	asm { @"10*3/2=" } 
	__outn(10*3/2); 
	asm { @"\n" }

	asm { @"10*5+2=" } 
	__outn(10*5+2); 
	asm { @"\n" }

	asm { @"10+5*3=" } 
	__outn(10+5*3); 
	asm { @"\n" }

	asm { @"1==1 = " } 
	if( 1==1 ) { true(); } else { false(); }
	asm { @"\n" }

	asm { @"1==1 && 2==2 = " } 
	if( 1==1 && 2==2 ) { true(); } else { false(); }
	asm { @"\n" }

	asm { @"1==1 && 1==2 = " } 
	if( 1==1 && 1==2 ) { true(); } else { false(); }
	asm { @"\n" }

	asm { @"1==1 && 1==1 || 1==2 = " } 
	if( 1==1 && 1==1 || 1==2 ) { true(); } else { false(); }
	asm { @"\n" }

	asm { @"1==1 || 1==1 && 1==2 = " } 
	if( 1==1 || 1==1 && 1==2 ) { true(); } else { false(); }
	asm { @"\n" }
}

true()
{
	asm { @"true" }
}

false()
{
	asm { @"false" }
}