main()
{
	asm { @"10-5-2=" } 
	__outn(10-5-2); 
	asm { @"\n" }

	asm { @"10*3/2=" } 
	__outn(10*3/2); 
	asm { @"\n" }

	asm { @"10*5+2=" } 
	__outn(10*5+2); 
	asm { @"\n" }

	asm { @"10+5*3=" } 
	__outn(10+5*3); 
	asm { @"\n" }

	asm { @"1==1 = " } 
	if( 1==1 ) { true(); } else { false(); }
	asm { @"\n" }

	asm { @"1==1 && 2==2 = " } 
	if( 1==1 && 2==2 ) { true(); } else { false(); }
	asm { @"\n" }

	asm { @"1==1 && 1==2 = " } 
	if( 1==1 && 1==2 ) { true(); } else { false(); }
	asm { @"\n" }

	asm { @"1==1 && 1==1 || 1==2 = " } 
	if( 1==1 && 1==1 || 1==2 ) { true(); } else { false(); }
	asm { @"\n" }

	asm { @"1==1 || 1==1 && 1==2 = " } 
	if( 1==1 || 1==1 && 1==2 ) { true(); } else { false(); }
	asm { @"\n" }

	// from Hugh Satow
	wrln(1);
	wrln(-minus(2));
	a = 2; wrln(++a);
	a = 5; wrln(--a);
	a = 5; wrln(a++);
	a = 6; wrln(a--);
	a = 7; wrln(a);
	wrln(8+(!8));
	wrln(-(-9));
	wrln(--10);
	wrln((11-1)+1);
	// 4 combinations of ' -'|' -'' -'|' -'a
	a = 12; wrln( - -a);
	a = 14; wrln( -- a);
	a = 14; wrln(-  -a);
	a = 15; wrln(- - a);

}

true()
{
	asm { @"true" }
}

false()
{
	asm { @"false" }
}

minus(xx)
{
	return -xx;
}

wrln(nn)
{
	__outn(nn); __out('\n');
}

